baseURL = 'https://www.will-code-for-pay.com/'
languageCode = 'en-us'
title = 'Will Code For Pay - a blog about software engineering, life, and whatever...'
theme = 'bilberry-hugo-theme/v4'

[params]
    author = 'Sean Curtis'
    description = 'A blog about software engineering, life, and whatever...'
    paginate = 10
    keywords = 'blog,personal,software engineering'
    copyrightBy = "by Sean Curtis"
    copyrightUseCurrentYear = true
    # date format
    dateFormat = "2024-06-12"
    customimage = "/images/cali-orly.jpg"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup.goldmark.parser.attribute]
block = true
#[params.copyright]
#    prefix = 'Copyright'
#    holder = 'by Sean Curtis'
#    startYear = '2024'
#    suffix = 'The opinions expressed herein are my own and do not represent those of my employer or any other third-party views in any way. This work is licensed under a Creative Commons Attribution 4.0 International License.'
